### ISSUE TITLE
Provide a web-based remote control

### ISSUE THREAD

**Issue by duncan-bayne** [rlister/org-present#10]
Provide a web-based remote control to allow slide selection on a remote device (phone, tablet, watch ...)

**Comment by duncan-bayne** [comment]
I [hacked up something](https://github.com/duncan-bayne/presentations/blob/master/ruby-rspec/server.lisp) for a one-off presentation.  I'm going to build on that, with (hopefully) the following features:

 * presentation name
 * next, previous slide
 * tree-like summary
 * security (password? certificate?)

**Comment by Kazark** [comment]
@rlister I think this can be closed since @duncan-bayne broke out a separate `org-present-remote` package.

**Comment by duncan-bayne** [comment]
Heh - I should have closed this at the time.
