### ISSUE TITLE
Cursor disappears

### ISSUE THREAD

**Issue by pierwill** [rlister/org-present#14]
Cursor often disappears after returning to org-mode. 

(I am using the provided hooks. Emacs 26.1 Org 9.1.3)

**Comment by BonfaceKilz** [comment]
Have you found a solution for this?

**Comment by mcraveiro** [comment]
I normally just use ```org-present-hide-cursor``` and ```org-present-show-cursor```. These seem to work as intended.

**Comment by impaktor** [comment]
I think this issue could be closed.
