### ISSUE TITLE
Dependency on org 7

### ISSUE THREAD

**Issue by peterhoeg** [rlister/org-present#7]
Is there any particular reason org version 7 is a hard requirement? If I manually load org-present it works perfectly fine with org 8.

**Comment by peterhoeg** [comment]
@rlister Well, when I try to install using `package-install` I get 
````
(error "Package `org-7` is unavailable")
````
However, you seem to using the Package-Requires directive exactly the same way as everyone else. I'm super puzzled by this.

**Comment by facundoolano** [comment]
I have the same issue.
